Log added
andromash/jv-movie-theatre pull request #6
Opened 2020-10-15 10:45 UTC by andromash

2020-10-15 10:55 UTC, DariiaPikul requested changes

2020-10-15 10:55 UTC, DariiaPikul commented on src/main/java/com/hibernate/cinema/Main.java
> +    private static final Logger LOGGER = Logger.getLogger(Main.class);
```suggestion
    private static final Logger logger = Logger.getLogger(Main.class);
```

2020-10-15 10:55 UTC, DariiaPikul commented on src/main/java/com/hibernate/cinema/Main.java
> +    private static final Logger LOGGER = Logger.getLogger(Main.class);
<img width="676" alt="Screenshot 2020-10-15 at 13 54 27" src="https://user-images.githubusercontent.com/68664175/96114172-f4adc900-0eed-11eb-909a-34296c0ccbc1.png">

2020-10-15 11:02 UTC, DariiaPikul approved these changes

2020-10-16 08:51 UTC, dmytro-hryhoruk approved these changes

2020-10-16 08:53 UTC, merged